title: Vinyl Record Collection
description: A website to showcase a vinyl record collection
baseurl: "https://evankrocker.github.io/records/" # Update if deploying to a subpath
url: "https://evankrocker.github.io" # Update to your GitHub Pages URL

# Enable Jekyll Collections
collections:
  artists:
    output: true
  albums:
    output: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-pagination

# Gems for search and filtering
gems:
  - jekyll-ajax-search
